# Generated by Django 3.2 on 2021-04-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contacto', '0002_clientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='Email',
            field=models.EmailField(default='prueba@prueba.cl', max_length=250),
        ),
    ]
